# Generated by Django 4.1.1 on 2022-09-16 00:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='blog-images', verbose_name='Fotoğraf')),
                ('location', models.CharField(choices=[(0, 'Navbar'), (1, 'Footer')], default=0, max_length=1, verbose_name='Menü Konumu')),
                ('content', tinymce.models.HTMLField(verbose_name='Yazı')),
                ('seoTitle', models.CharField(max_length=200, verbose_name='SEO Başlık')),
                ('seoKeywords', models.CharField(max_length=300, verbose_name='Anahtar Kelimeler')),
                ('seoDescription', models.TextField(verbose_name='SEO Açıklama')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('status', models.IntegerField(choices=[(0, 'Taslak'), (1, 'Yayınla')], default=0, verbose_name='Durum')),
            ],
            options={
                'verbose_name': 'Sayfa',
                'verbose_name_plural': 'Sayfalar',
                'ordering': ['-createdOn'],
            },
        ),
    ]
