# Generated by Django 4.1.1 on 2022-09-14 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('status', models.IntegerField(choices=[(0, 'Taslak'), (1, 'Yayınla')], default=1, verbose_name='Durum')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['-createdOn'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Yazı')),
                ('seoTitle', models.CharField(max_length=200, unique=True, verbose_name='SEO Başlık')),
                ('seoKeywords', models.TextField(verbose_name='Anahtar Kelimeler')),
                ('seoDescription', models.TextField(verbose_name='SEO Açıklama')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('status', models.IntegerField(choices=[(0, 'Taslak'), (1, 'Yayınla')], default=0, verbose_name='Durum')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Yazı',
                'verbose_name_plural': 'Yazılar',
                'ordering': ['-createdOn'],
            },
        ),
    ]
