# Generated by Django 4.1.1 on 2022-09-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='seoKeywords',
            field=models.CharField(max_length=300, verbose_name='Anahtar Kelimeler'),
        ),
    ]
